# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8bf0abcd238ab64f090eabbc79b6bbd3885113c982d761573d694ccd59e58769f226ef4f918fd94fc4b38a033432821e770194f8ae20d3c4355ad384162c68d

test:
  secret_key_base: c372f957517a344ffece8123f31c0ec8804fdaf2ecb2a074bd9521dda49b61e6e4bc45c8588d43d90d2c87b91e0546ca548358a8c410b47f2db5bf85f2f96da2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
